package util.image.opencvMat.flags

import org.opencv.imgproc.Imgproc
import util.image.ImageFormat
import util.image.ImageFormat.ArgbProcessing
import util.image.ImageFormat.Bgr
import util.image.ImageFormat.Bgra
import util.image.ImageFormat.Gray
import util.image.ImageFormat.Rgb
import util.image.ImageFormat.RgbaOpenCV

/**
 * Enum representing all of OpenCV's color conversion flags.
 *
 * @property value
 */
@Suppress("unused")
enum class CConv(val value: Int?, val from: ImageFormat? = null, val to: ImageFormat? = null) {
  Identity(null),
  RgbaToArgb(value = null, from = RgbaOpenCV, to = ArgbProcessing),
  Bgr2Bgra(Imgproc.COLOR_BGR2BGRA, from = Bgr, to = Bgra),
  Rgb2Rgba(Imgproc.COLOR_RGB2RGBA, from = Rgb, to = RgbaOpenCV),
  Bgra2Bgr(Imgproc.COLOR_BGRA2BGR, from = Bgra, to = Bgr),
  Rgba2Rgb(Imgproc.COLOR_RGBA2RGB, from = RgbaOpenCV, to = Rgb),
  Bgr2Rgba(Imgproc.COLOR_BGR2RGBA, from = Bgr, to = RgbaOpenCV),
  Rgb2Bgra(Imgproc.COLOR_RGB2BGRA, from = Rgb, to = Bgra),
  Rgba2Bgr(Imgproc.COLOR_RGBA2BGR, from = RgbaOpenCV, to = Bgr),
  Bgra2Rgb(Imgproc.COLOR_BGRA2RGB, from = Bgra, to = Rgb),
  Bgr2Rgb(Imgproc.COLOR_BGR2RGB, from = Bgr, to = Rgb),
  Rgb2Bgr(Imgproc.COLOR_RGB2BGR, from = Rgb, to = Bgr),
  Bgra2Rgba(Imgproc.COLOR_BGRA2RGBA, from = Bgra, to = RgbaOpenCV),
  Rgba2Bgra(Imgproc.COLOR_RGBA2BGRA, from = RgbaOpenCV, to = Bgra),
  Bgr2Gray(Imgproc.COLOR_BGR2GRAY, from = Bgr, to = Gray),
  Rgb2Gray(Imgproc.COLOR_RGB2GRAY, from = Rgb, to = Gray),
  Gray2Bgr(Imgproc.COLOR_GRAY2BGR, from = Gray, to = Bgr),
  Gray2Rgb(Imgproc.COLOR_GRAY2RGB, from = Gray, to = Rgb),
  Gray2Bgra(Imgproc.COLOR_GRAY2BGRA, from = Gray, to = Bgra),
  Gray2Rgba(Imgproc.COLOR_GRAY2RGBA, from = Gray, to = RgbaOpenCV),
  Bgra2Gray(Imgproc.COLOR_BGRA2GRAY, from = Bgra, to = Gray),
  Rgba2Gray(Imgproc.COLOR_RGBA2GRAY, from = RgbaOpenCV, to = Gray),
  Bgr2Bgr565(Imgproc.COLOR_BGR2BGR565, from = Bgr),
  Rgb2Bgr565(Imgproc.COLOR_RGB2BGR565, from = Rgb),
  Bgr5652Bgr(Imgproc.COLOR_BGR5652BGR, to = Bgr),
  Bgr5652Rgb(Imgproc.COLOR_BGR5652RGB, to = Rgb),
  Bgra2Bgr565(Imgproc.COLOR_BGRA2BGR565, from = Bgra),
  Rgba2Bgr565(Imgproc.COLOR_RGBA2BGR565, from = RgbaOpenCV),
  Bgr5652Bgra(Imgproc.COLOR_BGR5652BGRA, to = Bgra),
  Bgr5652Rgba(Imgproc.COLOR_BGR5652RGBA, to = RgbaOpenCV),
  Gray2Bgr565(Imgproc.COLOR_GRAY2BGR565, from = Gray),
  Bgr5652Gray(Imgproc.COLOR_BGR5652GRAY, to = Gray),
  Bgr2Bgr555(Imgproc.COLOR_BGR2BGR555, from = Bgr),
  Rgb2Bgr555(Imgproc.COLOR_RGB2BGR555, from = Rgb),
  Bgr5552Bgr(Imgproc.COLOR_BGR5552BGR, to = Bgr),
  Bgr5552Rgb(Imgproc.COLOR_BGR5552RGB, to = Rgb),
  Bgra2Bgr555(Imgproc.COLOR_BGRA2BGR555, from = Bgra),
  Rgba2Bgr555(Imgproc.COLOR_RGBA2BGR555, from = RgbaOpenCV),
  Bgr5552Bgra(Imgproc.COLOR_BGR5552BGRA, to = Bgra),
  Bgr5552Rgba(Imgproc.COLOR_BGR5552RGBA, to = RgbaOpenCV),
  Gray2Bgr555(Imgproc.COLOR_GRAY2BGR555, from = Gray),
  Bgr5552Gray(Imgproc.COLOR_BGR5552GRAY, to = Gray),
  Bgr2Xyz(Imgproc.COLOR_BGR2XYZ, from = Bgr),
  Rgb2Xyz(Imgproc.COLOR_RGB2XYZ, from = Rgb),
  Xyz2Bgr(Imgproc.COLOR_XYZ2BGR, to = Bgr),
  Xyz2Rgb(Imgproc.COLOR_XYZ2RGB, to = Rgb),
  Bgr2YcrCb(Imgproc.COLOR_BGR2YCrCb, from = Bgr),
  Rgb2YcrCb(Imgproc.COLOR_RGB2YCrCb, from = Rgb),
  YcrCb2Bgr(Imgproc.COLOR_YCrCb2BGR, to = Bgr),
  YcrCb2Rgb(Imgproc.COLOR_YCrCb2RGB, to = Rgb),
  Bgr2Hsv(Imgproc.COLOR_BGR2HSV, from = Bgr),
  Rgb2Hsv(Imgproc.COLOR_RGB2HSV, from = Rgb),
  Bgr2Lab(Imgproc.COLOR_BGR2Lab, from = Bgr),
  Rgb2Lab(Imgproc.COLOR_RGB2Lab, from = Rgb),
  Bgr2Luv(Imgproc.COLOR_BGR2Luv, from = Bgr),
  Rgb2Luv(Imgproc.COLOR_RGB2Luv, from = Rgb),
  Bgr2Hls(Imgproc.COLOR_BGR2HLS, from = Bgr),
  Rgb2Hls(Imgproc.COLOR_RGB2HLS, from = Rgb),
  Hsv2Bgr(Imgproc.COLOR_HSV2BGR, to = Bgr),
  Hsv2Rgb(Imgproc.COLOR_HSV2RGB, to = Rgb),
  Lab2Bgr(Imgproc.COLOR_Lab2BGR, to = Bgr),
  Lab2Rgb(Imgproc.COLOR_Lab2RGB, to = Rgb),
  Luv2Bgr(Imgproc.COLOR_Luv2BGR, to = Bgr),
  Luv2Rgb(Imgproc.COLOR_Luv2RGB, to = Rgb),
  Hls2Bgr(Imgproc.COLOR_HLS2BGR, to = Bgr),
  Hls2Rgb(Imgproc.COLOR_HLS2RGB, to = Rgb),
  Bgr2HsvFull(Imgproc.COLOR_BGR2HSV_FULL, from = Bgr),
  Rgb2HsvFull(Imgproc.COLOR_RGB2HSV_FULL, from = Rgb),
  Bgr2HlsFull(Imgproc.COLOR_BGR2HLS_FULL, from = Bgr),
  Rgb2HlsFull(Imgproc.COLOR_RGB2HLS_FULL, from = Rgb),
  Hsv2BgrFull(Imgproc.COLOR_HSV2BGR_FULL),
  Hsv2RgbFull(Imgproc.COLOR_HSV2RGB_FULL),
  Hls2BgrFull(Imgproc.COLOR_HLS2BGR_FULL),
  Hls2RgbFull(Imgproc.COLOR_HLS2RGB_FULL),
  Lbgr2Lab(Imgproc.COLOR_LBGR2Lab),
  Lrgb2Lab(Imgproc.COLOR_LRGB2Lab),
  Lbgr2Luv(Imgproc.COLOR_LBGR2Luv),
  Lrgb2Luv(Imgproc.COLOR_LRGB2Luv),
  Lab2Lbgr(Imgproc.COLOR_Lab2LBGR),
  Lab2Lrgb(Imgproc.COLOR_Lab2LRGB),
  Luv2Lbgr(Imgproc.COLOR_Luv2LBGR),
  Luv2Lrgb(Imgproc.COLOR_Luv2LRGB),
  Bgr2Yuv(Imgproc.COLOR_BGR2YUV, from = Bgr),
  Rgb2Yuv(Imgproc.COLOR_RGB2YUV, from = Rgb),
  Yuv2Bgr(Imgproc.COLOR_YUV2BGR, to = Bgr),
  Yuv2Rgb(Imgproc.COLOR_YUV2RGB, to = Rgb),
  Yuv2RgbNv12(Imgproc.COLOR_YUV2RGB_NV12),
  Yuv2BgrNv12(Imgproc.COLOR_YUV2BGR_NV12),
  Yuv2RgbNv21(Imgproc.COLOR_YUV2RGB_NV21),
  Yuv2BgrNv21(Imgproc.COLOR_YUV2BGR_NV21),
  Yuv420Sp2Rgb(Imgproc.COLOR_YUV420sp2RGB, to = Rgb),
  Yuv420Sp2Bgr(Imgproc.COLOR_YUV420sp2BGR, to = Bgr),
  Yuv2RgbaNv12(Imgproc.COLOR_YUV2RGBA_NV12),
  Yuv2BgraNv12(Imgproc.COLOR_YUV2BGRA_NV12),
  Yuv2RgbaNv21(Imgproc.COLOR_YUV2RGBA_NV21),
  Yuv2BgraNv21(Imgproc.COLOR_YUV2BGRA_NV21),
  Yuv420Sp2Rgba(Imgproc.COLOR_YUV420sp2RGBA, to = RgbaOpenCV),
  Yuv420Sp2Bgra(Imgproc.COLOR_YUV420sp2BGRA, to = Bgra),
  Yuv2RgbYv12(Imgproc.COLOR_YUV2RGB_YV12),
  Yuv2BgrYv12(Imgproc.COLOR_YUV2BGR_YV12),
  Yuv2RgbIyuv(Imgproc.COLOR_YUV2RGB_IYUV),
  Yuv2BgrIyuv(Imgproc.COLOR_YUV2BGR_IYUV),
  Yuv2RgbI420(Imgproc.COLOR_YUV2RGB_I420),
  Yuv2BgrI420(Imgproc.COLOR_YUV2BGR_I420),
  Yuv420P2Rgb(Imgproc.COLOR_YUV420p2RGB, to = Rgb),
  Yuv420P2Bgr(Imgproc.COLOR_YUV420p2BGR, to = Bgr),
  Yuv2RgbaYv12(Imgproc.COLOR_YUV2RGBA_YV12),
  Yuv2BgraYv12(Imgproc.COLOR_YUV2BGRA_YV12),
  Yuv2RgbaIyuv(Imgproc.COLOR_YUV2RGBA_IYUV),
  Yuv2BgraIyuv(Imgproc.COLOR_YUV2BGRA_IYUV),
  Yuv2RgbaI420(Imgproc.COLOR_YUV2RGBA_I420),
  Yuv2BgraI420(Imgproc.COLOR_YUV2BGRA_I420),
  Yuv420P2Rgba(Imgproc.COLOR_YUV420p2RGBA, to = RgbaOpenCV),
  Yuv420P2Bgra(Imgproc.COLOR_YUV420p2BGRA, to = Bgra),
  Yuv2Gray420(Imgproc.COLOR_YUV2GRAY_420),
  Yuv2GrayNv21(Imgproc.COLOR_YUV2GRAY_NV21),
  Yuv2GrayNv12(Imgproc.COLOR_YUV2GRAY_NV12),
  Yuv2GrayYv12(Imgproc.COLOR_YUV2GRAY_YV12),
  Yuv2GrayIyuv(Imgproc.COLOR_YUV2GRAY_IYUV),
  Yuv2GrayI420(Imgproc.COLOR_YUV2GRAY_I420),
  Yuv420Sp2Gray(Imgproc.COLOR_YUV420sp2GRAY, to = Gray),
  Yuv420P2Gray(Imgproc.COLOR_YUV420p2GRAY, to = Gray),
  Yuv2RgbUyvy(Imgproc.COLOR_YUV2RGB_UYVY),
  Yuv2BgrUyvy(Imgproc.COLOR_YUV2BGR_UYVY),
  Yuv2RgbY422(Imgproc.COLOR_YUV2RGB_Y422),
  Yuv2BgrY422(Imgproc.COLOR_YUV2BGR_Y422),
  Yuv2RgbUynv(Imgproc.COLOR_YUV2RGB_UYNV),
  Yuv2BgrUynv(Imgproc.COLOR_YUV2BGR_UYNV),
  Yuv2RgbaUyvy(Imgproc.COLOR_YUV2RGBA_UYVY),
  Yuv2BgraUyvy(Imgproc.COLOR_YUV2BGRA_UYVY),
  Yuv2RgbaY422(Imgproc.COLOR_YUV2RGBA_Y422),
  Yuv2BgraY422(Imgproc.COLOR_YUV2BGRA_Y422),
  Yuv2RgbaUynv(Imgproc.COLOR_YUV2RGBA_UYNV),
  Yuv2BgraUynv(Imgproc.COLOR_YUV2BGRA_UYNV),
  Yuv2RgbYuy2(Imgproc.COLOR_YUV2RGB_YUY2),
  Yuv2BgrYuy2(Imgproc.COLOR_YUV2BGR_YUY2),
  Yuv2RgbYvyu(Imgproc.COLOR_YUV2RGB_YVYU),
  Yuv2BgrYvyu(Imgproc.COLOR_YUV2BGR_YVYU),
  Yuv2RgbYuyv(Imgproc.COLOR_YUV2RGB_YUYV),
  Yuv2BgrYuyv(Imgproc.COLOR_YUV2BGR_YUYV),
  Yuv2RgbYunv(Imgproc.COLOR_YUV2RGB_YUNV),
  Yuv2BgrYunv(Imgproc.COLOR_YUV2BGR_YUNV),
  Yuv2RgbaYuy2(Imgproc.COLOR_YUV2RGBA_YUY2),
  Yuv2BgraYuy2(Imgproc.COLOR_YUV2BGRA_YUY2),
  Yuv2RgbaYvyu(Imgproc.COLOR_YUV2RGBA_YVYU),
  Yuv2BgraYvyu(Imgproc.COLOR_YUV2BGRA_YVYU),
  Yuv2RgbaYuyv(Imgproc.COLOR_YUV2RGBA_YUYV),
  Yuv2BgraYuyv(Imgproc.COLOR_YUV2BGRA_YUYV),
  Yuv2RgbaYunv(Imgproc.COLOR_YUV2RGBA_YUNV),
  Yuv2BgraYunv(Imgproc.COLOR_YUV2BGRA_YUNV),
  Yuv2GrayUyvy(Imgproc.COLOR_YUV2GRAY_UYVY),
  Yuv2GrayYuy2(Imgproc.COLOR_YUV2GRAY_YUY2),
  Yuv2GrayY422(Imgproc.COLOR_YUV2GRAY_Y422),
  Yuv2GrayUynv(Imgproc.COLOR_YUV2GRAY_UYNV),
  Yuv2GrayYvyu(Imgproc.COLOR_YUV2GRAY_YVYU),
  Yuv2GrayYuyv(Imgproc.COLOR_YUV2GRAY_YUYV),
  Yuv2GrayYunv(Imgproc.COLOR_YUV2GRAY_YUNV),
  Rgba2MRgba(Imgproc.COLOR_RGBA2mRGBA, from = RgbaOpenCV),
  MRgba2Rgba(Imgproc.COLOR_mRGBA2RGBA, from = RgbaOpenCV, to = RgbaOpenCV),
  Rgb2YuvI420(Imgproc.COLOR_RGB2YUV_I420, from = Rgb),
  Bgr2YuvI420(Imgproc.COLOR_BGR2YUV_I420, from = Bgr),
  Rgb2YuvIyuv(Imgproc.COLOR_RGB2YUV_IYUV, from = Rgb),
  Bgr2YuvIyuv(Imgproc.COLOR_BGR2YUV_IYUV, from = Bgr),
  Rgba2YuvI420(Imgproc.COLOR_RGBA2YUV_I420, from = RgbaOpenCV),
  Bgra2YuvI420(Imgproc.COLOR_BGRA2YUV_I420, from = Bgra),
  Rgba2YuvIyuv(Imgproc.COLOR_RGBA2YUV_IYUV, from = RgbaOpenCV),
  Bgra2YuvIyuv(Imgproc.COLOR_BGRA2YUV_IYUV, from = Bgra),
  Rgb2YuvYv12(Imgproc.COLOR_RGB2YUV_YV12, from = Rgb),
  Bgr2YuvYv12(Imgproc.COLOR_BGR2YUV_YV12, from = Bgr),
  Rgba2YuvYv12(Imgproc.COLOR_RGBA2YUV_YV12, from = RgbaOpenCV),
  Bgra2YuvYv12(Imgproc.COLOR_BGRA2YUV_YV12, from = Bgra),
  BayerBg2Bgr(Imgproc.COLOR_BayerBG2BGR, to = Bgr),
  BayerGb2Bgr(Imgproc.COLOR_BayerGB2BGR, to = Bgr),
  BayerRg2Bgr(Imgproc.COLOR_BayerRG2BGR, to = Bgr),
  BayerGr2Bgr(Imgproc.COLOR_BayerGR2BGR, to = Bgr),
  BayerBg2Rgb(Imgproc.COLOR_BayerBG2RGB, to = Rgb),
  BayerGb2Rgb(Imgproc.COLOR_BayerGB2RGB, to = Rgb),
  BayerRg2Rgb(Imgproc.COLOR_BayerRG2RGB, to = Rgb),
  BayerGr2Rgb(Imgproc.COLOR_BayerGR2RGB, to = Rgb),
  BayerBg2Gray(Imgproc.COLOR_BayerBG2GRAY, to = Gray),
  BayerGb2Gray(Imgproc.COLOR_BayerGB2GRAY, to = Gray),
  BayerRg2Gray(Imgproc.COLOR_BayerRG2GRAY, to = Gray),
  BayerGr2Gray(Imgproc.COLOR_BayerGR2GRAY, to = Gray),
  BayerBg2BgrVng(Imgproc.COLOR_BayerBG2BGR_VNG),
  BayerGb2BgrVng(Imgproc.COLOR_BayerGB2BGR_VNG),
  BayerRg2BgrVng(Imgproc.COLOR_BayerRG2BGR_VNG),
  BayerGr2BgrVng(Imgproc.COLOR_BayerGR2BGR_VNG),
  BayerBg2RgbVng(Imgproc.COLOR_BayerBG2RGB_VNG),
  BayerGb2RgbVng(Imgproc.COLOR_BayerGB2RGB_VNG),
  BayerRg2RgbVng(Imgproc.COLOR_BayerRG2RGB_VNG),
  BayerGr2RgbVng(Imgproc.COLOR_BayerGR2RGB_VNG),
  BayerBg2BgrEa(Imgproc.COLOR_BayerBG2BGR_EA),
  BayerGb2BgrEa(Imgproc.COLOR_BayerGB2BGR_EA),
  BayerRg2BgrEa(Imgproc.COLOR_BayerRG2BGR_EA),
  BayerGr2BgrEa(Imgproc.COLOR_BayerGR2BGR_EA),
  BayerBg2RgbEa(Imgproc.COLOR_BayerBG2RGB_EA),
  BayerGb2RgbEa(Imgproc.COLOR_BayerGB2RGB_EA),
  BayerRg2RgbEa(Imgproc.COLOR_BayerRG2RGB_EA),
  BayerGr2RgbEa(Imgproc.COLOR_BayerGR2RGB_EA),
  BayerBg2Bgra(Imgproc.COLOR_BayerBG2BGRA, to = Bgra),
  BayerGb2Bgra(Imgproc.COLOR_BayerGB2BGRA, to = Bgra),
  BayerRg2Bgra(Imgproc.COLOR_BayerRG2BGRA, to = Bgra),
  BayerGr2Bgra(Imgproc.COLOR_BayerGR2BGRA, to = Bgra),
  BayerBg2Rgba(Imgproc.COLOR_BayerBG2RGBA, to = RgbaOpenCV),
  BayerGb2Rgba(Imgproc.COLOR_BayerGB2RGBA, to = RgbaOpenCV),
  BayerRg2Rgba(Imgproc.COLOR_BayerRG2RGBA, to = RgbaOpenCV),
  BayerGr2Rgba(Imgproc.COLOR_BayerGR2RGBA, to = RgbaOpenCV),
  ColorCvtMax(Imgproc.COLOR_COLORCVT_MAX),
  ;

  val isIdentity: Boolean get() = this === Identity

  companion object {
    fun getCConv(from: ImageFormat, to: ImageFormat): CConv {
      if (from == to) return Identity
      return values().find { it.from == from && it.to == to }
        ?: throw Exception("Couldn't find CConv match for from: $from and to: $to")
    }
  }
}
